In [6]:
import pandas as pd 
import numpy as np

## Exercise 1 : Wildlife Strikes

#### Part 1 - Import and Explore Data

#####  1. Import the dataset strikes.csv with the functions read_csv of the library pandas

In [ ]:
# Import the data
# read into a DataFrame variable for reuse

strikes = pd.read_csv(r'C:\Users\ASUS\Desktop\Term2 DS\W4 - Data Preprocessing\Strikes.csv')
strikes.head()

,INDEX_NR,OPID,OPERATOR,ATYPE,AMA,AMO,EMA,EMO,AC_CLASS,AC_MASS,...,REPORTED_NAME,REPORTED_TITLE,REPORTED_DATE,SOURCE,PERSON,NR_INJURIES,NR_FATALITIES,LUPDATE,TRANSFER,INDICATED_DAMAGE
73,17458,MIL,MILITARY,C-135,148,NaN,NaN,NaN,A,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
74,17459,MIL,MILITARY,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
75,17460,MIL,MILITARY,C-40,148,NaN,22.0,NaN,A,4.0,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
76,17461,MIL,MILITARY,T-38,665,NaN,22.0,62.0,A,2.0,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,1
77,17462,MIL,MILITARY,H-60,813,NaN,NaN,NaN,B,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0

##### 2. Exploration of the data

In [24]:
# a. Shapes of the data
# using the variable we created during import
w = strikes.shape
w

# (row 78, colunm 94)

(78, 94)

In [25]:
# b. Display the four first rows of the DataFrame, the five last rows
# write your code here
display(strikes.head(4))  #display kbal 4
display(strikes.tail(5))  #display ktuy 5

,INDEX_NR,OPID,OPERATOR,ATYPE,AMA,AMO,EMA,EMO,AC_CLASS,AC_MASS,...,REPORTED_NAME,REPORTED_TITLE,REPORTED_DATE,SOURCE,PERSON,NR_INJURIES,NR_FATALITIES,LUPDATE,TRANSFER,INDICATED_DAMAGE
0,100000,AAL,AMERICAN AIRLINES,B-727,148,10.0,34.0,10.0,A,4.0,...,Deleted,Deleted,1992-05-14 00:00:00,FAA Form 5200-7,Pilot,NaN,NaN,1996-03-14 00:00:00,0,0
1,100001,UAL,UNITED AIRLINES,B-737-300,148,24.0,10.0,1.0,A,4.0,...,Deleted,Deleted,NaN,Air Transport Report,Air Transport Operations,NaN,NaN,2007-12-20 00:00:00,0,0
2,100002,UAL,UNITED AIRLINES,B-737-300,148,24.0,10.0,1.0,A,4.0,...,Deleted,Deleted,NaN,Air Transport Report,Air Transport Operations,NaN,NaN,2007-12-20 00:00:00,0,0
3,100003,UAL,UNITED AIRLINES,B-757-200,148,26.0,34.0,40.0,A,4.0,...,Deleted,Deleted,NaN,Air Transport Report,Air Transport Operations,NaN,NaN,2007-12-20 00:00:00,0,0

,INDEX_NR,OPID,OPERATOR,ATYPE,AMA,AMO,EMA,EMO,AC_CLASS,AC_MASS,...,REPORTED_NAME,REPORTED_TITLE,REPORTED_DATE,SOURCE,PERSON,NR_INJURIES,NR_FATALITIES,LUPDATE,TRANSFER,INDICATED_DAMAGE
73,17458,MIL,MILITARY,C-135,148,NaN,NaN,NaN,A,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
74,17459,MIL,MILITARY,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
75,17460,MIL,MILITARY,C-40,148,NaN,22.0,NaN,A,4.0,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0
76,17461,MIL,MILITARY,T-38,665,NaN,22.0,62.0,A,2.0,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,1
77,17462,MIL,MILITARY,H-60,813,NaN,NaN,NaN,B,NaN,...,Deleted,Deleted,NaN,BASH,NaN,NaN,NaN,2014-09-18 00:00:00,0,0

In [ ]:
# c. Display the columns and row names
# write your code here
print("columns:", strikes.columns.tolist())
print("rows  :", strikes.index.tolist())

columns: ['INDEX_NR', 'OPID', 'OPERATOR', 'ATYPE', 'AMA', 'AMO', 'EMA', 'EMO', 'AC_CLASS', 'AC_MASS', 'NUM_ENGS', 'TYPE_ENG', 'ENG_1_POS', 'ENG_2_POS', 'ENG_3_POS', 'ENG_4_POS', 'REG', 'FLT', 'REMAINS_COLLECTED', 'REMAINS_SENT', 'INCIDENT_DATE', 'INCIDENT_MONTH', 'INCIDENT_YEAR', 'TIME_OF_DAY', 'TIME', 'AIRPORT_ID', 'AIRPORT', 'STATE', 'FAAREGION', 'ENROUTE', 'RUNWAY', 'LOCATION', 'HEIGHT', 'SPEED', 'DISTANCE', 'PHASE_OF_FLT', 'DAMAGE', 'STR_RAD', 'DAM_RAD', 'STR_WINDSHLD', 'DAM_WINDSHLD', 'STR_NOSE', 'DAM_NOSE', 'STR_ENG1', 'DAM_ENG1', 'STR_ENG2', 'DAM_ENG2', 'STR_ENG3', 'DAM_ENG3', 'STR_ENG4', 'DAM_ENG4', 'INGESTED', 'STR_PROP', 'DAM_PROP', 'STR_WING_ROT', 'DAM_WING_ROT', 'STR_FUSE', 'DAM_FUSE', 'STR_LG', 'DAM_LG', 'STR_TAIL', 'DAM_TAIL', 'STR_LGHTS', 'DAM_LGHTS', 'STR_OTHER', 'DAM_OTHER', 'OTHER_SPECIFY', 'EFFECT', 'EFFECT_OTHER', 'SKY', 'PRECIP', 'SPECIES_ID', 'SPECIES', 'BIRDS_SEEN', 'BIRDS_STRUCK', 'SIZE', 'WARNED', 'COMMENTS', 'REMARKS', 'AOS', 'COST_REPAIRS', 'COST_OTHER', 'COST_REPAIRS_INFL_ADJ', 'COST_OTHER_INFL_ADJ', 'REPORTED_NAME', 'REPORTED_TITLE', 'REPORTED_DATE', 'SOURCE', 'PERSON', 'NR_INJURIES', 'NR_FATALITIES', 'LUPDATE', 'TRANSFER', 'INDICATED_DAMAGE']
rows  : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]

In [19]:
# d.	Get the number of occurances of birdstrike for each airline operator using the function value_count(). Save this number into the variable operator_counts. What is the type of this variable?  //pandas.Series
# write your code here

# now the column is guaranteed to be 'operator'
operator_counts = strikes['OPERATOR'].value_counts()
operator_counts
# type(operator_counts)

OPERATOR
UNKNOWN                           13
UNITED AIRLINES                   10
AMERICAN AIRLINES                  9
SKYWEST AIRLINES                   6
MILITARY                           5
UPS AIRLINES                       3
BUSINESS                           3
FEDEX EXPRESS                      3
SOUTHWEST AIRLINES                 2
PINNACLE                           2
CONTINENTAL AIRLINES               2
ATLANTIC SOUTHEAST                 2
ABX AIR                            2
MESA AIRLINES                      2
EXPRESSJET AIRLINES                2
AIR MIDWEST                        1
AMERICAN EAGLE AIRLINES            1
COMAIR AIRLINES                    1
WINGS WEST                         1
AMERICA WEST AIRLINES              1
CHAUTAUQUA AIRLINES                1
EXPRESSJET (CONTINENTAL EXPRS)     1
AIRTRAN AIRWAYS                    1
CAPE AIR                           1
HORIZON AIR                        1
SUN COUNTRY AIRLINES               1
ENDEAVOR AIR                       1
Name: count, dtype: int64

In [23]:
# e. Save the Operator name in a variable
# write your code here
operator_name = strikes['OPERATOR'].unique()

operator_name

<StringArray>
[             'AMERICAN AIRLINES',                'UNITED AIRLINES',
                    'AIR MIDWEST',             'SOUTHWEST AIRLINES',
                       'PINNACLE',        'AMERICAN EAGLE AIRLINES',
                'COMAIR AIRLINES',           'CONTINENTAL AIRLINES',
                     'WINGS WEST',                        'UNKNOWN',
               'SKYWEST AIRLINES',          'AMERICA WEST AIRLINES',
             'ATLANTIC SOUTHEAST',                   'UPS AIRLINES',
                       'BUSINESS',            'CHAUTAUQUA AIRLINES',
                  'FEDEX EXPRESS', 'EXPRESSJET (CONTINENTAL EXPRS)',
                        'ABX AIR',                'AIRTRAN AIRWAYS',
                  'MESA AIRLINES',                       'CAPE AIR',
            'EXPRESSJET AIRLINES',                    'HORIZON AIR',
           'SUN COUNTRY AIRLINES',                   'ENDEAVOR AIR',
                       'MILITARY']
Length: 27, dtype: str

In [29]:
# f. Save the counts in another variable transforming the dataframe operator_counts into a numpy array.
# write your code here
counts = operator_counts.values
print(counts)
type(counts)

[13 10  9  6  5  3  3  3  2  2  2  2  2  2  2  1  1  1  1  1  1  1  1  1
  1  1  1]

numpy.ndarray

#### Part 2 - Data Cleaning

##### Missing Value:

# 1. Check the number of missing values per columns. 

3.	Decide: 
a.	Which columns should be dropped ?
b.	Which columns should be filled ?
c.	Fill missing values

In [28]:
# write your code here

# print(strikes.head())
# print(strikes.info())

In [ ]:
# 2.	Calculated the percentages of missing values. 
# write your code here

In [ ]:
# 3.	Decide: 
        # a.	Which columns should be dropped ?
        # b.	Which columns should be filled ?
        # c.	Fill missing values

In [ ]:
# write your code here

In [ ]:
# 4.	We now want to create barplots using the libraries matplotlib and seaborn to visualize occurances of birdstrike per airline operator. Comment the following lines

## Exercise 2: Survival on titanic dataset

#### Part 1 - Importation of the data and description of the dataset

In [ ]:
# 1.	In the first practical session, download the dataset and set the dataset as Dataframe. 
# write your code here

In [ ]:
# 2.	Describe the dataset titanic: features, nature of the features, number of observations. 
# write your code here

In [ ]:
# 3.	Basic statistics: mean of each variable, quartiles
# write your code here

In [ ]:
# 4.	Percentage of missing values for each column. Sort by descending values.
# write your code here

#### Part 2: Remove Irrelevant Features
Remove : 
-	PassengerId
-	Ticket
-	Name
Explain why these columns are removed. ( 2 – 3 Paragraph). (Write in Markdown)

#### Part 3: Missing Values 

# write your code here

In [ ]:
# 1.	Compute missing value percentages.

In [ ]:
# 2.	Handing missing values:
# •	Age -> median 
# •	Embarked -> mode 
# •	Cabin -> drop or justify decision

Part 4: Encoding
Encode: 
-	Sex
-	Embarked 
Use: 
-	Label Encoding or one-hot Encoding

In [ ]:
# write your code here

#### Part 5: Scaling
1.	Scale numerical features: 
•	Age 
•	Fare
Use:
•	Min-Max Scaling or Standardization

In [ ]:
# write your code here

#### Part 6: Outlier Detection

In [ ]:
# 1.	Detect outlier in Dare using IQR 
# write your code here

In [ ]:
# 2. Visualization using boxplot 
# write your code here

In [ ]:
# 3.	Explain whether you remove them or not ?
# write your code here

Basic graphic analysis
We want to understand what features could contributes to a high survival rate. It would make sense if everything would be correlated with a high survival rate. 
1.	We focus on the features ‘Age’ and ‘Sex’
a.	Separate the dataset into men and women 
b.	Display the distribution of the age survivors and non survivors according to the ‘Sex’. 
2.	At first glance is there some link between ‘Embarked’ and ‘Survival’. 
3.	At first glance is there some link between ‘Pclass’ and ‘Survival’.

Write your explaination in the markdowns !

write your explain here !